# frozen_string_literal: true

ruby '2.6.3'

source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'sinatra', '~> 2.0'
gem 'sinatra-contrib', '~> 2.0'
gem 'thin', '~> 1.7'

gem 'graphql-client', '~> 0.16'
gem 'http', '~> 4.2'

group :development do
  gem 'rubocop', '~> 0.76', require: false
end

group :test do
  gem 'rack-test', '~> 1.1'
end
