# frozen_string_literal: true

require 'rake/testtask'
require 'dotenv/tasks'

task default: 'test'

Rake::TestTask.new do |task|
  task.pattern = 'test/**/*_test.rb'
end

namespace :graphql do
  task dump_schemas: :dotenv do
    require_relative 'lib/apis/github_api'

    GraphQL::Client.dump_schema(GithubApi::HTTP, GithubApi::SCHEMA_PATH)

    puts 'Succesfully dumped GitHub API schema'
  end
end
