# frozen_string_literal: true

require 'rake/testtask'

task default: 'test'

Rake::TestTask.new do |task|
  task.pattern = 'test/**/*_test.rb'
end

task 'graphql:dump_schemas' do
  require_relative 'github'

  GraphQL::Client.dump_schema(GithubApi::HTTP, GithubApi::SCHEMA_PATH)

  puts 'Succesfully dumped GitHub API schema'
end
